# Generated by Django 3.2.5 on 2021-07-23 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256, verbose_name='Название шаблона')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.TextField(max_length=256, verbose_name='Имя поля')),
                ('type_field', models.TextField(choices=[(django.db.models.fields.EmailField, 'email'), (django.db.models.fields.DateTimeField, 'date'), ('phone', 'phone'), (models.TextField(max_length=500), 'text')], max_length=5, verbose_name='Тип поля')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webformval.template', verbose_name='Шаблон')),
            ],
        ),
    ]
